//! pipeline_native — the parent of the native-emission capability tree
//! (PLUGGABLE_NESTED_TRANSFORMS.md §1).
//!
//! A small set of parents in the renderer recognize the shapes (a
//! `pipeline(printf LITERAL, consumer)`, an exec call in condition or
//! statement position, a `cat <<'EOF'` heredoc, a `(grep && echo) || echo`
//! control chain), build a [`NativeCtx`], and dispatch to the per-command
//! capability leaves in `capabilities/`. The dispatch (module list + linear
//! attempt) is generated by `build.rs` from the `capabilities/` directory —
//! so adding a capability = dropping a file there and rebuilding; no
//! transform edits a shared hand-maintained `match`.

use crate::ir::{IrExpr, IrStmt};

// The real capability-leaf modules (mod list generated by build.rs, since
// `mod path` must resolve against the source tree, not OUT_DIR).
pub(crate) mod capabilities;

/// Everything a pipeline-capability leaf needs to emit native perl, prepared
/// once by the parent so leaves never walk the tree themselves.
#[derive(Clone)]
pub(crate) struct PipelineCtx {
    /// the consumer command name (e.g. "sort")
    pub cmd: String,
    /// the consumer's option words (e.g. ["-n"])
    pub words: Vec<String>,
    /// the producer's literal payload, already a perl string literal
    pub content_perl: String,
}

/// What a capability leaf produced: a boolean expression (for if/while
/// conditions) or a complete perl statement (with status + output).
pub(crate) enum NativeEmit {
    Cond(String),
    Stmt(String),
}

/// The shape a parent recognized, handed to the capability leaves. Leaves
/// self-gate on the shape + command; nothing here walks the tree.
pub(crate) enum NativeCtx<'a> {
    /// `printf LITERAL | <consumer>` (payload prepared by the parent)
    Pipe(&'a PipelineCtx),
    /// an exec call: `cond=true` in if/while condition, `false` as a statement
    Exec { call: &'a IrExpr, cond: bool },
    /// a `cat <<'EOF' … EOF` heredoc body (already unescaped literal)
    Heredoc(&'a str),
    /// a `(grep -q PAT FILE && echo A) || echo B` control chain
    Chain(&'a IrExpr),
}

// The generated `native_dispatch` comes from OUT_DIR (built by build.rs from
// the capabilities/ directory).
include!(concat!(env!("OUT_DIR"), "/pipeline_native_gen.rs"));

/// Parent (pipeline): recognize a 2-stage `pipeline(producer, consumer)`
/// where the producer is a single literal printf; hand the consumer to the
/// tree. `None` => not ours => the caller shells out.
pub(crate) fn native_pipeline(e: &IrExpr) -> Option<String> {
    let IrExpr::Call { func, args } = e else {
        return None;
    };
    if func != "pipeline" {
        return None;
    }
    let [IrExpr::Array(stages)] = args.as_slice() else {
        return None;
    };
    if stages.len() != 2 {
        return None;
    }
    let [IrExpr::Arrow(s1), IrExpr::Arrow(s2)] = stages.as_slice() else {
        return None;
    };
    let content = pipe_printf_content(s1)?;
    let (cmd, words) = pipe_consumer(s2)?;
    let ctx = PipelineCtx {
        cmd,
        words,
        content_perl: crate::ir::safe_perl_q_string(&content),
    };
    match native_dispatch(&NativeCtx::Pipe(&ctx)) {
        Some(NativeEmit::Stmt(s)) => Some(s),
        _ => None,
    }
}

/// Parent (exec-in-condition): `grep -q PAT FILE` / `cmp -s F1 F2` etc.
/// return a boolean expression for an if/while cond.
pub(crate) fn native_exec_cond(call: &IrExpr) -> Option<String> {
    match native_dispatch(&NativeCtx::Exec { call, cond: true }) {
        Some(NativeEmit::Cond(s)) => Some(s),
        _ => None,
    }
}

/// Parent (exec-statement): `cmp -s F1 F2` as a statement → a full perl
/// status assignment.
pub(crate) fn native_exec_stmt(call: &IrExpr) -> Option<String> {
    match native_dispatch(&NativeCtx::Exec { call, cond: false }) {
        Some(NativeEmit::Stmt(s)) => Some(s),
        _ => None,
    }
}

/// Parent (cat-heredoc): the body of a verified `cat <<'EOF' … EOF` → a
/// native print statement.
pub(crate) fn native_heredoc(body: &str) -> Option<String> {
    match native_dispatch(&NativeCtx::Heredoc(body)) {
        Some(NativeEmit::Stmt(s)) => Some(s),
        _ => None,
    }
}

/// Parent (control chain): `(grep -q PAT FILE && echo A) || echo B` → a
/// native if/else statement.
pub(crate) fn native_chain(e: &IrExpr) -> Option<String> {
    match native_dispatch(&NativeCtx::Chain(e)) {
        Some(NativeEmit::Stmt(s)) => Some(s),
        _ => None,
    }
}

/// The literal payload of a `printf LITERAL` first stage (single no-`%`
/// format: escapes interpreted, no conversions).
fn pipe_printf_content(s: &[IrStmt]) -> Option<String> {
    let [IrStmt::Expr(e)] = s else {
        return None;
    };
    let IrExpr::Call { func, args } = e else {
        return None;
    };
    if !matches!(func.as_str(), "exec" | "builtin") {
        return None;
    }
    let [IrExpr::Str(cmd, _), IrExpr::Array(words)] = args.as_slice() else {
        return None;
    };
    if cmd != "printf" || words.len() != 1 {
        return None;
    }
    let fmt = crate::ir::grep_lit_str(&words[0])?;
    if fmt.contains('%') {
        return None;
    }
    Some(printf_unescape(&fmt))
}

/// The consumer command + option words of the second stage.
fn pipe_consumer(s: &[IrStmt]) -> Option<(String, Vec<String>)> {
    let [IrStmt::Expr(e)] = s else {
        return None;
    };
    let IrExpr::Call { func, args } = e else {
        return None;
    };
    if !matches!(func.as_str(), "exec" | "builtin") {
        return None;
    }
    let [IrExpr::Str(cmd, _), IrExpr::Array(words)] = args.as_slice() else {
        return None;
    };
    let words: Vec<String> = words
        .iter()
        .filter_map(|w| crate::ir::grep_lit_str(w))
        .collect();
    Some((cmd.clone(), words))
}

/// Parse `-c <decimal>` from an option list; other option forms refuse.
pub(crate) fn exact_num(words: &[String], opt: &str) -> Option<i64> {
    let mut n = None;
    let mut it = words.iter();
    while let Some(w) = it.next() {
        if w == opt {
            n = it.next().and_then(|v| v.parse().ok());
        } else if !w.starts_with('-') {
            return None;
        }
    }
    n
}

/// printf's backslash escapes (`\n \t \r \\`); enough for literal payloads.
fn printf_unescape(s: &str) -> String {
    let mut out = String::new();
    let mut it = s.chars();
    while let Some(c) = it.next() {
        if c != '\\' {
            out.push(c);
            continue;
        }
        match it.next() {
            Some('n') => out.push('\n'),
            Some('t') => out.push('\t'),
            Some('r') => out.push('\r'),
            Some('\\') => out.push('\\'),
            Some(o) => {
                out.push('\\');
                out.push(o);
            }
            None => {}
        }
    }
    out
}
