//! pipeline_native — the parent of the "single-line producer | consumer"
//! capability tree (PLUGGABLE_NESTED_TRANSFORMS.md §1).
//!
//! The parent walks the tree ONCE (recognizing `pipeline(printf LITERAL,
//! consumer)`), extracts a ready [`PipelineCtx`], and dispatches to the
//! per-command capability leaves in `capabilities/`. The dispatch (module
//! list + linear attempt) is generated by `build.rs` from the
//! `capabilities/` directory — so adding a consumer = dropping a file there
//! and rebuilding; no transform edits a shared hand-maintained `match`.

use crate::ir::{IrExpr, IrStmt};

// The real capability-leaf modules (mod list generated by build.rs, since
// `mod path` must resolve against the source tree, not OUT_DIR).
pub(crate) mod capabilities;

/// Everything a capability leaf needs to emit native perl, prepared once by
/// the parent so leaves never walk the tree themselves.
#[derive(Clone)]
pub(crate) struct PipelineCtx {
    /// the consumer command name (e.g. "sort")
    pub cmd: String,
    /// the consumer's option words (e.g. ["-n"])
    pub words: Vec<String>,
    /// the producer's literal payload, already a perl string literal
    pub content_perl: String,
}

// The generated `native_pipeline_dispatch` comes from OUT_DIR (built by
// build.rs from the capabilities/ directory).
include!(concat!(env!("OUT_DIR"), "/pipeline_native_gen.rs"));

/// Parent: recognize a 2-stage `pipeline(producer, consumer)` where the
/// producer is a single literal printf, and hand the consumer to the
/// capability tree. `None` => not ours => the caller shells out.
pub(crate) fn native_pipeline(e: &IrExpr) -> Option<String> {
    let IrExpr::Call { func, args } = e else {
        return None;
    };
    if func != "pipeline" {
        return None;
    }
    let [IrExpr::Array(stages)] = args.as_slice() else {
        return None;
    };
    if stages.len() != 2 {
        return None;
    }
    let [IrExpr::Arrow(s1), IrExpr::Arrow(s2)] = stages.as_slice() else {
        return None;
    };
    let content = pipe_printf_content(s1)?;
    let (cmd, words) = pipe_consumer(s2)?;
    let ctx = PipelineCtx {
        cmd,
        words,
        content_perl: crate::ir::safe_perl_q_string(&content),
    };
    native_pipeline_dispatch(&ctx)
}

/// The literal payload of a `printf LITERAL` first stage (single no-`%`
/// format: escapes interpreted, no conversions).
fn pipe_printf_content(s: &[IrStmt]) -> Option<String> {
    let [IrStmt::Expr(e)] = s else {
        return None;
    };
    let IrExpr::Call { func, args } = e else {
        return None;
    };
    if !matches!(func.as_str(), "exec" | "builtin") {
        return None;
    }
    let [IrExpr::Str(cmd, _), IrExpr::Array(words)] = args.as_slice() else {
        return None;
    };
    if cmd != "printf" || words.len() != 1 {
        return None;
    }
    let fmt = crate::ir::grep_lit_str(&words[0])?;
    if fmt.contains('%') {
        return None;
    }
    Some(printf_unescape(&fmt))
}

/// The consumer command + option words of the second stage.
fn pipe_consumer(s: &[IrStmt]) -> Option<(String, Vec<String>)> {
    let [IrStmt::Expr(e)] = s else {
        return None;
    };
    let IrExpr::Call { func, args } = e else {
        return None;
    };
    if !matches!(func.as_str(), "exec" | "builtin") {
        return None;
    }
    let [IrExpr::Str(cmd, _), IrExpr::Array(words)] = args.as_slice() else {
        return None;
    };
    let words: Vec<String> = words
        .iter()
        .filter_map(|w| crate::ir::grep_lit_str(w))
        .collect();
    Some((cmd.clone(), words))
}

/// Parse `-c <decimal>` from an option list; other option forms refuse.
pub(crate) fn exact_num(words: &[String], opt: &str) -> Option<i64> {
    let mut n = None;
    let mut it = words.iter();
    while let Some(w) = it.next() {
        if w == opt {
            n = it.next().and_then(|v| v.parse().ok());
        } else if !w.starts_with('-') {
            return None;
        }
    }
    n
}

/// printf's backslash escapes (`\n \t \r \\`); enough for literal payloads.
fn printf_unescape(s: &str) -> String {
    let mut out = String::new();
    let mut it = s.chars();
    while let Some(c) = it.next() {
        if c != '\\' {
            out.push(c);
            continue;
        }
        match it.next() {
            Some('n') => out.push('\n'),
            Some('t') => out.push('\t'),
            Some('r') => out.push('\r'),
            Some('\\') => out.push('\\'),
            Some(o) => {
                out.push('\\');
                out.push(o);
            }
            None => {}
        }
    }
    out
}
