//! render_ext — the perl renderer's drop-in registry for transform-declared
//! (Ext) nodes (PLUGGABLE_NESTED_TRANSFORMS.md §3 / the per-backend layer).
//!
//! `emit_stmt`'s `IrStmt::Ext` arm calls [`render_ext`], which dispatches on
//! the node's tag to a handler in `handlers/` (the drop-in directory; the
//! dispatch is generated by build.rs). A handler renders its node by calling
//! the perl renderer's OWN emitters for the fields it knows — the
//! recursion goes back through the generated match, so a handler never
//! re-implements rendering. Backends without a handler keep the loud
//! refusal (the marketplace `refuse > guess`).

use crate::shir_nodes::ExtNode;

// The handler-leaf modules (mod list generated by build.rs into the source
// tree, since `mod path` must resolve there, not in OUT_DIR).
pub(crate) mod handlers;

/// The render context a handler needs: the output buffer + indent, and the
/// perl renderer's emitters (which the handler calls for its children).
pub(crate) struct RenderCtx<'a> {
    pub out: &'a mut String,
    pub indent: usize,
}

// The generated tag → handler dispatch (build.rs scans handlers/).
include!(concat!(env!("OUT_DIR"), "/render_ext_gen.rs"));

/// Render an Ext node on the perl backend. Returns true iff handled; false
/// means the caller keeps the loud refusal.
pub(crate) fn render_ext(out: &mut String, n: &dyn ExtNode, indent: usize) -> bool {
    render_ext_dispatch(&mut RenderCtx { out, indent }, n)
}
