//! build.rs — generate the `pipeline_native` capability tree
//! (PLUGGABLE_NESTED_TRANSFORMS.md §1).
//!
//! Each `.rs` file in `src/pipeline_native/capabilities/` is one capability
//! leaf exposing `pub(crate) fn emit(ctx: &PipelineCtx) -> Option<String>`
//! (self-gating on `ctx.cmd`). This script emits:
//!   1. `src/pipeline_native/capabilities/mod.rs` — the `mod` list (the real
//!      modules must live in the source tree for `mod path` resolution).
//!   2. `OUT_DIR/pipeline_native_gen.rs` — the linear `native_pipeline_dispatch`.
//! Adding a consumer = dropping a `.rs` file into the directory.
use std::{env, fs, path::Path};

fn main() {
    let caps_dir = Path::new("src/pipeline_native/capabilities");
    println!("cargo:rerun-if-changed={}", caps_dir.display());

    let mut leaves: Vec<String> = Vec::new();
    if let Ok(rd) = fs::read_dir(caps_dir) {
        for entry in rd
            .filter_map(Result::ok)
            .filter(|e| e.file_type().map(|t| t.is_file()).unwrap_or(false))
        {
            let n = entry.file_name().to_string_lossy().into_owned();
            if !n.ends_with(".rs") || n == "mod.rs" {
                continue;
            }
            leaves.push(n.trim_end_matches(".rs").to_string());
        }
    }
    leaves.sort();
    leaves.dedup();

    let mut mods = String::new();
    for name in &leaves {
        mods.push_str(&format!("pub(crate) mod {name};\n"));
    }
    fs::write(
        caps_dir.join("mod.rs"),
        format!("// @generated by build.rs — do not edit.\n{mods}\n"),
    )
    .unwrap();

    let mut chain = String::new();
    for name in &leaves {
        chain.push_str(&format!(
            "    if let Some(s) = capabilities::{name}::emit(ctx) {{\n        return Some(s);\n    }}\n"
        ));
    }
    let out = env::var("OUT_DIR").unwrap_or_default();
    let gen = format!(
        "// @generated by build.rs — do not edit.\n\
         pub(crate) fn native_pipeline_dispatch(ctx: &PipelineCtx) -> Option<String> {{\n{chain}    None\n    }}\n"
    );
    fs::write(format!("{out}/pipeline_native_gen.rs"), gen).unwrap();
}
