//! build.rs — generate the `pipeline_native` capability tree
//! (PLUGGABLE_NESTED_TRANSFORMS.md §1) and the `shir_nodes` transform-
//! declared IR-node union + JSON (PLUGGABLE_NESTED_TRANSFORMS.md §2).
//!
//! Part 1 — capabilities: each `.rs` in
//! `src/pipeline_native/capabilities/` is a leaf exposing
//! `pub(crate) fn emit(ctx: &NativeCtx) -> Option<NativeEmit>`. Emits the
//! `mod` list (source tree, for `mod path` resolution) + a linear
//! `native_dispatch` (OUT_DIR).
//!
//! Part 2 — IR nodes: each `src/shir_nodes/*.node` is a node declaration
//! (`node NAME` / `tag "X"` / `field NAME: string|int|bool|expr|stmts`).
//! Emits, into OUT_DIR: the generated `struct` + inherent `from_json` +
//! `impl ExtNode` (to_json / tag / children_mut) + `all_nodes()` — the
//! union of every transform-declared node, with JSON generator and parser
//! both derived from the same declaration (they cannot drift).
use std::{env, fs, path::Path};

fn main() {
    // ── Part 1: capability tree ────────────────────────────────────────
    let caps_dir = Path::new("src/pipeline_native/capabilities");
    println!("cargo:rerun-if-changed={}", caps_dir.display());
    let mut leaves: Vec<String> = Vec::new();
    if let Ok(rd) = fs::read_dir(caps_dir) {
        for entry in rd
            .filter_map(Result::ok)
            .filter(|e| e.file_type().map(|t| t.is_file()).unwrap_or(false))
        {
            let n = entry.file_name().to_string_lossy().into_owned();
            if !n.ends_with(".rs") || n == "mod.rs" {
                continue;
            }
            leaves.push(n.trim_end_matches(".rs").to_string());
        }
    }
    leaves.sort();
    leaves.dedup();

    let mut mods = String::new();
    for name in &leaves {
        mods.push_str(&format!("pub(crate) mod {name};\n"));
    }
    fs::write(
        caps_dir.join("mod.rs"),
        format!("// @generated by build.rs — do not edit.\n{mods}\n"),
    )
    .unwrap();

    let mut chain = String::new();
    for name in &leaves {
        chain.push_str(&format!(
            "    if let Some(s) = capabilities::{name}::emit(ctx) {{\n        return Some(s);\n    }}\n"
        ));
    }
    let out = env::var("OUT_DIR").unwrap_or_default();
    let gen = format!(
        "// @generated by build.rs — do not edit.\n\
         pub(crate) fn native_dispatch(ctx: &NativeCtx) -> Option<NativeEmit> {{\n{chain}    None\n    }}\n"
    );
    fs::write(format!("{out}/pipeline_native_gen.rs"), gen).unwrap();

    // ── Part 2: transform-declared IR nodes ────────────────────────────
    let nodes_dir = Path::new("src/shir_nodes");
    println!("cargo:rerun-if-changed={}", nodes_dir.display());
    let all_nodes = parse_nodes(nodes_dir);

    // Split into stmt (ExtNode) and expr (ExtExpr) nodes
    let stmt_nodes: Vec<&NodeDecl> = all_nodes.iter().filter(|n| !n.is_expr).collect();
    let expr_nodes: Vec<&NodeDecl> = all_nodes.iter().filter(|n| n.is_expr).collect();

    // Stmt nodes → ExtNode structs + all_nodes() registry
    let node_gen = gen_stmt_nodes(&stmt_nodes);
    fs::write(format!("{out}/shir_nodes_gen.rs"), node_gen).unwrap();

    // Expr nodes → ExtExpr structs + all_expr_nodes() registry
    let expr_gen = gen_expr_nodes(&expr_nodes);
    fs::write(format!("{out}/shir_expr_nodes_gen.rs"), expr_gen).unwrap();

    // ── Part 3: per-backend Ext-node render handlers (perl proof) ──────
    // DISABLED for scratch: using hand-written gen_stmt.rs / gen_expr.rs
    // Stub render_ext_gen.rs so the include! in render_ext/mod.rs works.
    fs::write(
        format!("{out}/render_ext_gen.rs"),
        "// @generated stub — disabled for scratch\n \
         pub(crate) fn render_ext_dispatch(_ctx: &mut crate::render_ext::RenderCtx, _n: &dyn crate::shir_nodes::ExtNode) -> bool { false }\n"
    ).unwrap();

    // ── Part 4: render_ext_expr dispatch (IrExpr::Ext handlers) ───────
    let expr_handler_dir = Path::new("src/render_ext_expr/handlers");
    println!("cargo:rerun-if-changed={}", expr_handler_dir.display());
    let mut expr_hmods = String::new();
    let mut expr_hchain = String::new();
    if let Ok(rd) = fs::read_dir(expr_handler_dir) {
        for entry in rd
            .filter_map(Result::ok)
            .filter(|e| e.file_type().map(|t| t.is_file()).unwrap_or(false))
        {
            let file = entry.file_name().to_string_lossy().into_owned();
            if !file.ends_with(".rs") || file == "mod.rs" {
                continue;
            }
            let hname = file.trim_end_matches(".rs").to_string();
            // Map snake_case handler name to PascalCase tag
            // field_extract → FieldExtract
            let tag: String = hname.split('_')
                .map(|w| { let mut c = w.chars();
                    match c.next() {
                        None => String::new(),
                        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                    }
                })
                .collect();
            expr_hmods.push_str(&format!("    pub(crate) mod {hname};\n"));
            expr_hchain.push_str(&format!(
                "        \"{tag}\" => handlers::{hname}::render(n.as_any().downcast_ref::<crate::shir_nodes::{tag}>().expect(\"tag/type agree\"), ctx),\n",
                tag = tag, hname = hname
            ));
        }
    }
    // Write the handlers mod.rs (source tree, for mod path resolution)
    fs::write(
        expr_handler_dir.join("mod.rs"),
        format!("// @generated by build.rs — do not edit.\n{expr_hmods}\n"),
    ).unwrap();
    // Write the dispatch fn (OUT_DIR)
    let dispatch = format!(
        "// @generated by build.rs — do not edit.\n\
         pub(crate) fn render_ext_expr_dispatch(n: &dyn crate::shir_nodes::ExtExpr, ctx: &crate::render_ext_expr::ExprRenderCtx) -> Option<String> {{\n\
         match n.tag() {{\n{expr_hchain}        _ => None,\n    }}\n}}\n"
    );
    fs::write(format!("{out}/render_ext_expr_gen.rs"), dispatch).unwrap();
}

/// snake_case of a CamelCase identifier ("CountedFor" → "counted_for").
fn snake(name: &str) -> String {
    let mut out = String::new();
    for (i, c) in name.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.extend(c.to_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

/// One parsed node declaration.
struct NodeDecl {
    name: String,
    tag: String,
    is_expr: bool, // kind: expr → ExtExpr; kind: stmt (default) → ExtNode
    fields: Vec<(String, String)>, // (field name, field type)
}

fn parse_nodes(dir: &Path) -> Vec<NodeDecl> {
    let mut out = Vec::new();
    if let Ok(rd) = fs::read_dir(dir) {
        for entry in rd.filter_map(Result::ok) {
            let path = entry.path();
            if path.extension().map(|e| e == "node").unwrap_or(false) {
                if let Ok(text) = fs::read_to_string(&path) {
                    if let Some(n) = parse_one_node(&text) {
                        out.push(n);
                    }
                }
            }
        }
    }
    out.sort_by(|a, b| a.name.cmp(&b.name));
    out
}

fn parse_one_node(text: &str) -> Option<NodeDecl> {
    let mut name = None;
    let mut tag = None;
    let mut is_expr = false;
    let mut fields = Vec::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some(rest) = line.strip_prefix("node ") {
            name = Some(rest.trim().to_string());
        } else if let Some(rest) = line.strip_prefix("tag ") {
            tag = Some(rest.trim_matches('"').to_string());
        } else if let Some(rest) = line.strip_prefix("kind ") {
            is_expr = rest.trim() == "expr";
        } else if let Some(rest) = line.strip_prefix("field ") {
            if let Some((fname, ftype)) = rest.split_once(':') {
                fields.push((fname.trim().to_string(), ftype.trim().to_string()));
            }
        }
    }
    Some(NodeDecl {
        name: name?,
        tag: tag.unwrap_or_default(),
        is_expr,
        fields,
    })
}

// ── Field type helpers ───────────────────────────────────────────────

fn rust_ty(ftype: &str) -> &'static str {
    match ftype {
        "string" => "String",
        "int" => "i64",
        "bool" => "bool",
        "expr" => "crate::ir::IrExpr",
        "stmts" => "Vec<crate::ir::IrStmt>",
        "optional_string" => "Option<String>",
        "optional_expr" => "Option<Box<crate::ir::IrExpr>>",
        "vec_field_range" => "Vec<crate::ir::FieldRange>",
        other => panic!("unknown shir_nodes field type {other}"),
    }
}

fn gen_json_build(fname: &str, ftype: &str) -> String {
    let raw = match ftype {
        "string" | "optional_string" | "vec_field_range" => {
            format!("            \"{fname}\": self.{fname}.clone(),\n")
        }
        "int" => format!("            \"{fname}\": self.{fname},\n"),
        "bool" => format!("            \"{fname}\": self.{fname},\n"),
        "expr" => format!(
            "            \"{fname}\": crate::shir_nodes::enc::expr_to_json(&self.{fname}),\n"
        ),
        "optional_expr" => format!(
            "            \"{fname}\": self.{fname}.as_ref().map(|e| crate::shir_nodes::enc::expr_to_json(e)),\n"
        ),
        "stmts" => format!(
            "            \"{fname}\": crate::shir_nodes::enc::stmts_to_json(&self.{fname}),\n"
        ),
        _ => String::new(),
    };
    // vec_field_range uses serde_json::to_value which handles the derive
    if ftype == "vec_field_range" {
        raw.replace(
            &format!("self.{fname}.clone()"),
            &format!("serde_json::to_value(&self.{fname}).unwrap()"),
        )
    } else {
        raw
    }
}

fn gen_json_read(fname: &str, ftype: &str, struct_name: &str) -> String {
    match ftype {
        "string" => format!(
            "v[\"{fname}\"].as_str().ok_or(\"{struct_name}.{fname}\")?.to_string()"
        ),
        "int" => format!("v[\"{fname}\"].as_i64().ok_or(\"{struct_name}.{fname}\")?"),
        "bool" => format!("v[\"{fname}\"].as_bool().ok_or(\"{struct_name}.{fname}\")?"),
        "optional_string" => format!("v[\"{fname}\"].as_str().map(|s| s.to_string())"),
        "expr" => format!("crate::shir_nodes::enc::json_to_expr(&v[\"{fname}\"])?"),
        "optional_expr" => format!(
            "if v[\"{fname}\"].is_null() {{ None }} else {{ Some(Box::new(crate::shir_nodes::enc::json_to_expr(&v[\"{fname}\"])?)) }}"
        ),
        "stmts" => format!("crate::shir_nodes::enc::json_to_stmts(&v[\"{fname}\"])?"),
        "vec_field_range" => format!(
            "serde_json::from_value(v[\"{fname}\"].clone()).map_err(|e| format!(\"{struct_name}.{fname}: {{e}}\"))?"
        ),
        _ => String::new(),
    }
}

// ── Statement node generation (ExtNode) ─────────────────────────────

fn gen_stmt_node(n: &NodeDecl) -> String {
    let mut fields = String::new();
    let mut json_build = String::new();
    let mut json_read_lines = Vec::new();
    let mut children = String::new();
    let mut children_ref = String::new();

    for (fname, ftype) in &n.fields {
        let ty = rust_ty(ftype);
        fields.push_str(&format!("    pub {fname}: {ty},\n"));
        json_build.push_str(&gen_json_build(fname, ftype));
        json_read_lines.push(format!(
            "            {fname}: {}", gen_json_read(fname, ftype, &n.name)
        ));
        if ftype == "stmts" {
            children.push_str(&format!("        out.extend(self.{fname}.iter_mut());\n"));
            children_ref.push_str(&format!("        out.extend(self.{fname}.iter());\n"));
        }
    }

    let json_read = json_read_lines.join(",\n");

    format!(
        r#"// @generated by build.rs from a shir_nodes/*.node — do not edit.
#[derive(Debug, Clone, PartialEq)]
pub struct {name} {{
{fields}}}

impl {name} {{
    pub(crate) fn from_json(v: &serde_json::Value) -> Result<Self, String> {{
        Ok({name} {{
{json_read}
        }})
    }}
}}

impl crate::shir_nodes::ExtNode for {name} {{
    fn tag(&self) -> &'static str {{ "{tag}" }}
    fn to_json(&self) -> serde_json::Value {{
        serde_json::json!({{
            "type": "{tag}",
{json_build}        }})
    }}
    fn children_mut(&mut self) -> Vec<&mut crate::ir::IrStmt> {{
        let mut out = Vec::new();
{children}        out
    }}
    fn children(&self) -> Vec<&crate::ir::IrStmt> {{
        let mut out = Vec::new();
{children_ref}        out
    }}
    fn clone_box(&self) -> Box<dyn crate::shir_nodes::ExtNode> {{
        Box::new(self.clone())
    }}
    fn as_any(&self) -> &dyn std::any::Any {{ self }}
}}

"#,
        name = n.name,
        tag = n.tag,
        fields = fields,
        json_read = json_read,
        json_build = json_build,
        children = children,
        children_ref = children_ref,
    )
}

fn gen_stmt_nodes(nodes: &[&NodeDecl]) -> String {
    let mut out = String::new();
    for n in nodes {
        out.push_str(&gen_stmt_node(n));
    }
    let mut registry = String::new();
    for n in nodes {
        registry.push_str(&format!(
            "        (\"{tag}\", |v| Ok(Box::new({name}::from_json(v)?))),\n",
            tag = n.tag, name = n.name
        ));
    }
    out.push_str(&format!(
        "// @generated by build.rs — the union of transform-declared stmt nodes.\n\
         pub(crate) fn all_nodes() -> Vec<(&'static str, crate::shir_nodes::NodeCtor)> {{\n\
         vec![\n{registry}    ]\n}}\n"
    ));
    out
}

// ── Expression node generation (ExtExpr) ────────────────────────────

fn gen_expr_node(n: &NodeDecl) -> String {
    let mut fields = String::new();
    let mut json_build = String::new();
    let mut json_read_lines = Vec::new();
    let mut child_exprs = String::new();
    let mut child_exprs_ref = String::new();

    for (fname, ftype) in &n.fields {
        let ty = rust_ty(ftype);
        fields.push_str(&format!("    pub {fname}: {ty},\n"));
        json_build.push_str(&gen_json_build(fname, ftype));
        json_read_lines.push(format!(
            "            {fname}: {}", gen_json_read(fname, ftype, &n.name)
        ));
        if ftype == "expr" {
            child_exprs.push_str(&format!("        out.push(&mut self.{fname});\n"));
            child_exprs_ref.push_str(&format!("        out.push(&self.{fname});\n"));
        } else if ftype == "optional_expr" {
            child_exprs.push_str(&format!(
                "        if let Some(ref mut e) = self.{fname} {{ out.push(e); }}\n"
            ));
            child_exprs_ref.push_str(&format!(
                "        if let Some(ref e) = self.{fname} {{ out.push(e); }}\n"
            ));
        }
    }

    let json_read = json_read_lines.join(",\n");

    format!(
        r#"// @generated by build.rs from a shir_nodes/*.node — do not edit.
#[derive(Debug, Clone, PartialEq)]
pub struct {name} {{
{fields}}}

impl {name} {{
    pub(crate) fn from_json(v: &serde_json::Value) -> Result<Self, String> {{
        Ok({name} {{
{json_read}
        }})
    }}
}}

impl crate::shir_nodes::ExtExpr for {name} {{
    fn tag(&self) -> &'static str {{ "{tag}" }}
    fn to_json(&self) -> serde_json::Value {{
        serde_json::json!({{
            "type": "{tag}",
{json_build}        }})
    }}
    fn children_mut(&mut self) -> Vec<&mut crate::ir::IrExpr> {{
        let mut out = Vec::new();
{child_exprs}        out
    }}
    fn children(&self) -> Vec<&crate::ir::IrExpr> {{
        let mut out = Vec::new();
{child_exprs_ref}        out
    }}
    fn clone_box(&self) -> Box<dyn crate::shir_nodes::ExtExpr> {{
        Box::new(self.clone())
    }}
    fn as_any(&self) -> &dyn std::any::Any {{ self }}
}}

"#,
        name = n.name,
        tag = n.tag,
        fields = fields,
        json_read = json_read,
        json_build = json_build,
        child_exprs = child_exprs,
        child_exprs_ref = child_exprs_ref,
    )
}

fn gen_expr_nodes(nodes: &[&NodeDecl]) -> String {
    let mut out = String::new();
    for n in nodes {
        out.push_str(&gen_expr_node(n));
    }
    let mut registry = String::new();
    for n in nodes {
        registry.push_str(&format!(
            "        (\"{tag}\", |v| Ok(Box::new({name}::from_json(v)?))),\n",
            tag = n.tag, name = n.name
        ));
    }
    out.push_str(&format!(
        "// @generated by build.rs — the union of transform-declared expr nodes.\n\
         pub(crate) fn all_expr_nodes() -> Vec<(&'static str, crate::shir_nodes::ExprNodeCtor)> {{\n\
         vec![\n{registry}    ]\n}}\n"
    ));
    out
}
