#!/bin/sh
#
# Generated by sh2perl (sh backend). Non-POSIX constructs used:
# - 'local': variable scoping (POSIX sh lacks local, but dash/bash/zsh support it)
# - Array emulation (name_0, name_len): arrays are not POSIX
# - '(( ))' arithmetic: required for integer comparison in conditions
# - 'grep -P' helper: PCRE not in POSIX, checked at runtime
#

# portable PCRE grep: GNU grep -P, macOS gnu-grep, pcregrep/pcre2grep, or perl
grep_p() {
    _gp_flags=
    while [ "$#" -gt 0 ]; do
        case "$1" in
            --) shift; break ;;
            -*) _gp_flags="$_gp_flags $1"; shift ;;
            *) break ;;
        esac
    done
    [ "$#" -eq 0 ] && return 1
    _gp_pat="$1"; shift
    if grep -P $_gp_flags -- "$_gp_pat" "$@" 2>/dev/null; then return; fi
    if command -v ggrep >/dev/null 2>&1; then ggrep -P $_gp_flags -- "$_gp_pat" "$@"; return; fi
    if command -v pcre2grep >/dev/null 2>&1; then pcre2grep $_gp_flags "$_gp_pat" "$@"; return; fi
    if command -v pcregrep >/dev/null 2>&1; then pcregrep $_gp_flags "$_gp_pat" "$@"; return; fi
    case "$_gp_flags" in
        *-o*) perl -ne 'BEGIN{$p=shift @ARGV} while (/$p/g) { print "$&\n" }' "$_gp_pat" "$@" ;;
        *)    perl -ne 'BEGIN{$p=shift @ARGV} print if /$p/' "$_gp_pat" "$@" ;;
    esac
}

case x in *(?<![:-])\b\w+*) true;; *) false;; esac
