//! render_ext_estree — drop-in handler registry for ExtExpr nodes on the
//! ESTree backend (native JS rendering).
//!
//! Mirrors `render_ext_expr` but produces `estree::Expr` AST nodes
//! instead of rendered text. Each handler file in `handlers/` renders
//! one tag; build.rs scans the directory and generates the tag →
//! handler dispatch. The shir.rs `IrExpr::Ext` arm consults this BEFORE
//! the hand-written `ext_to_native_estree` table, so a new node gets
//! native ESTree rendering by dropping in a `.node` declaration + one
//! handler file — zero edits to shared core files.

// The handler-leaf modules (mod list generated by build.rs).
pub(crate) mod handlers;

// The generated tag → handler dispatch (build.rs scans handlers/).
include!(concat!(env!("OUT_DIR"), "/render_ext_estree_gen.rs"));

/// Render an ExtExpr node to native ESTree. Returns Some(expr) if a
/// handler exists, None otherwise (caller falls back to its own table /
/// the sh2.* call).
pub(crate) fn render(n: &dyn crate::shir_nodes::ExtExpr) -> Option<crate::estree::Expr> {
    render_ext_estree_dispatch(n)
}
