//! render_ext_expr — drop-in handler registry for ExtExpr nodes.
//!
//! Mirrors `render_ext` (for IrStmt::Ext) but for IrExpr::Ext.
//! Each handler file in `handlers/` renders one tag; build.rs scans
//! the directory and generates the tag → handler dispatch.
//!
//! A backend's `IrExpr::Ext` arm calls `render_ext_expr::render()`;
//! if no handler exists, it returns None and the backend falls back
//! to the sh2.* call.

use crate::shir_nodes::ExtExpr;

/// Render context for expression handlers.
pub(crate) struct ExprRenderCtx {
    pub indent: usize,
}

// The handler-leaf modules (mod list generated by build.rs).
pub(crate) mod handlers;

// The generated tag → handler dispatch (build.rs scans handlers/).
include!(concat!(env!("OUT_DIR"), "/render_ext_expr_gen.rs"));

/// Render an ExtExpr node. Returns Some(perl_code) if a handler exists,
/// None otherwise (caller falls back to sh2.* call).
pub(crate) fn render(n: &dyn ExtExpr, ctx: &ExprRenderCtx) -> Option<String> {
    render_ext_expr_dispatch(n, ctx)
}
