// @generated by build.rs — do not edit.
pub(crate) mod cat;
pub(crate) mod cmp;
pub(crate) mod grep;
pub(crate) mod head;
pub(crate) mod ls;
pub(crate) mod sort;
pub(crate) mod tail;
pub(crate) mod typeset;
pub(crate) mod unset;
pub(crate) mod wc;

