#!/usr/bin/env perl
use strict;
use warnings;
use Carp;
use English qw(-no_match_vars $ERRNO $EVAL_ERROR $INPUT_RECORD_SEPARATOR $OS_ERROR $PROGRAM_NAME);
use IPC::Open3;
use File::Path qw(make_path remove_tree);
my $main_exit_code = 0;
my $ls_success = 0;
our $CHILD_ERROR;
$0 = '000__04f_output_formatting.sh';
print "=== Output and Formatting Commands ===\n";
my $echo_result = do { my $__cs = "Hello from backticks"; chomp $__cs; $__cs; };
print "Echo result: ${echo_result}\n";
my $printf_result = do { my $__cs = sprintf("Number: %d, String: %s\n", 42, "test");
; chomp $__cs; $__cs; };
print "Printf result: ${printf_result}\n";
my $tee_result = do { open(my $__fh, '-|', 'bash', '-c', q{echo 'test output' | tee test_tee.txt}) or die "cmd failed: $!\n"; my $_r = do { local $/; <$__fh> }; close $__fh; chomp $_r; $CHILD_ERROR = $? >> 8; $_r; };
print "Tee result: ${tee_result}\n";
unlink('test_tee.txt');
print "=== Output and Formatting Commands Complete ===\n";
