#!/usr/bin/env perl
use strict;
use warnings;
use File::Basename;

# DEBUG: Collected 16 variables: ["file_content", "grep_result", "sed_result", "awk_result", "sort_result", "uniq_result", "word_count", "line_count", "head_result", "tail_result", "cut_result", "paste_result", "comm_result", "diff_result", "tr_result", "xargs_result"]
my $file_content = 0;
my $grep_result = 0;
my $sed_result = 0;
my $awk_result = 0;
my $sort_result = 0;
my $uniq_result = 0;
my $word_count = 0;
my $line_count = 0;
my $head_result = 0;
my $tail_result = 0;
my $cut_result = 0;
my $paste_result = 0;
my $comm_result = 0;
my $diff_result = 0;
my $tr_result = 0;
my $xargs_result = 0;

print("=== Text Processing Commands ===\n");
$file_content = `cat 000__04c_text_processing_commands.sh | head -5`;
$ENV{file_content} = $file_content;
print("First 5 lines of this file:\n");
print($file_content . "\n");
$grep_result = `grep -n "echo" 000__04c_text_processing_commands.sh`;
$ENV{grep_result} = $grep_result;
print("Lines containing \'echo\':\n");
print($grep_result . "\n");
$sed_result = `echo "Hello World" | sed 's/World/Universe/'`;
$ENV{sed_result} = $sed_result;
print(("Sed result: " . $sed_result) . "\n");
$awk_result = `echo "1 2 3 4 5" | awk '{print $1 + $2}'`;
$ENV{awk_result} = $awk_result;
print(("Awk sum result: " . $awk_result) . "\n");
$sort_result = `echo -e "zebra\napple\nbanana" | sort`;
$ENV{sort_result} = $sort_result;
print("Sorted words:\n");
print($sort_result . "\n");
$uniq_result = `echo -e "apple\napple\nbanana\nbanana\ncherry" | uniq`;
$ENV{uniq_result} = $uniq_result;
print("Unique words:\n");
print($uniq_result . "\n");
$word_count = `echo "Hello World" | wc -w`;
$ENV{word_count} = $word_count;
$line_count = `echo -e "line1\nline2\nline3" | wc -l`;
$ENV{line_count} = $line_count;
print(("Word count: " . $word_count) . "\n");
print(("Line count: " . $line_count) . "\n");
$head_result = `seq 1 10 | head -3`;
$ENV{head_result} = $head_result;
print(("First 3 numbers: " . $head_result) . "\n");
$tail_result = `seq 1 10 | tail -3`;
$ENV{tail_result} = $tail_result;
print(("Last 3 numbers: " . $tail_result) . "\n");
$cut_result = `echo "apple:banana:cherry" | cut -d: -f2`;
$ENV{cut_result} = $cut_result;
print(("Second field: " . $cut_result) . "\n");
local *STDOUT; open(STDOUT, '>', 'temp1.txt') or die "Cannot open file: $!\n";
print("1\n2\n3");
local *STDOUT; open(STDOUT, '>', 'temp2.txt') or die "Cannot open file: $!\n";
print("a\nb\nc");
$paste_result = `paste temp1.txt temp2.txt`;
$ENV{paste_result} = $paste_result;
print("Pasted columns:\n");
print($paste_result . "\n");
unlink('temp1.txt');
unlink('temp2.txt');
local *STDOUT; open(STDOUT, '>', 'file1.txt') or die "Cannot open file: $!\n";
print("apple\nbanana\ncherry");
local *STDOUT; open(STDOUT, '>', 'file2.txt') or die "Cannot open file: $!\n";
print("banana\ncherry\ndate");
$comm_result = `comm -12 file1.txt file2.txt`;
$ENV{comm_result} = $comm_result;
print("Common lines:\n");
print($comm_result . "\n");
$diff_result = `diff file1.txt file2.txt`;
$ENV{diff_result} = $diff_result;
print("File differences:\n");
print($diff_result . "\n");
$tr_result = `echo "HELLO WORLD" | tr 'A-Z' 'a-z'`;
$ENV{tr_result} = $tr_result;
print(("Lowercase: " . $tr_result) . "\n");
$xargs_result = `echo "1 2 3" | xargs -n1 echo "Number:"`;
$ENV{xargs_result} = $xargs_result;
print("Xargs result:\n");
print($xargs_result . "\n");
unlink('file1.txt');
unlink('file2.txt');
print("=== Text Processing Commands Complete ===\n");