#!/usr/bin/env perl
use strict;
use warnings;
use File::Basename;

# DEBUG: Collected 5 variables: ["cp_result", "mv_result", "rm_result", "mkdir_result", "touch_result"]
my $cp_result = 0;
my $mv_result = 0;
my $rm_result = 0;
my $mkdir_result = 0;
my $touch_result = 0;

print("=== File Manipulation Commands ===\n");
print("=== cp command ===\n");
print("\n");
local *STDOUT; open(STDOUT, '>', 'test_file.txt') or die "Cannot open file: $!\n";
print("test content\n");
$cp_result = `cp test_file.txt test_file_copy.txt && echo "Copy successful"`;
$ENV{cp_result} = $cp_result;
print(("Copy result: " . $cp_result) . "\n");
my $pipeline_result_1 = system('ls test_file.txt test_file_copy.txt test_file_moved.txt 2>/dev/null') == 0 || (print("No test files found\n"));
print("\n");
print("=== mv command ===\n");
$mv_result = `mv test_file_copy.txt test_file_moved.txt && echo "Move successful"`;
$ENV{mv_result} = $mv_result;
print(("Move result: " . $mv_result) . "\n");
my $pipeline_result_2 = system('ls test_file.txt test_file_copy.txt test_file_moved.txt 2>/dev/null') == 0 || (print("No test files found\n"));
print("\n");
print("=== rm command ===\n");
$rm_result = `rm test_file.txt test_file_moved.txt && echo "Remove successful"`;
$ENV{rm_result} = $rm_result;
print(("Remove result: " . $rm_result) . "\n");
my $pipeline_result_3 = system('ls test_file.txt test_file_copy.txt test_file_moved.txt 2>/dev/null') == 0 || (print("No test files found\n"));
print("\n");
print("=== mkdir command ===\n");
$mkdir_result = `mkdir test_dir && echo "Directory created"`;
$ENV{mkdir_result} = $mkdir_result;
print(("Mkdir result: " . $mkdir_result) . "\n");
open(my $fh, '>', 'test_dir/file') or die "Cannot create file: $!\n";
close($fh);
my $pipeline_result_4 = system('ls test_dir 2>/dev/null') == 0 || (print("Directory not found\n"));
unlink('test_dir/file') or die "Cannot remove file: $!\n";
system("rmdir", "test_dir");
print("\n");
print("=== touch command ===\n");
$touch_result = `touch test_file.txt && echo "File touched"`;
$ENV{touch_result} = $touch_result;
print(("Touch result: " . $touch_result) . "\n");
print("\n");
unlink('test_file.txt');
unlink('test_file_copy.txt');
unlink('test_file_moved.txt');
my $pipeline_result_5 = system('rm -rf test_dir 2>/dev/null') == 0 || system('true') == 0;