// @generated by build.rs from src/shir_nodes/*.node — do not edit.
// (scratch copy for compilation verification)

use crate::ir::IrExpr;

// ── FieldExtract ─────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq)]
pub struct FieldExtract {
    pub text: IrExpr,
    pub delimiter: String,
    pub fields: Vec<crate::ir::FieldRange>,
    pub suppress_no_delim: bool,
    pub output_delimiter: Option<String>,
}

impl FieldExtract {
    pub(crate) fn from_json(v: &serde_json::Value) -> Result<Self, String> {
        Ok(FieldExtract {
            text: crate::shir_nodes::enc::json_to_expr(&v["text"])?,
            delimiter: v["delimiter"].as_str().ok_or("FieldExtract.delimiter")?.to_string(),
            fields: vec![], // TODO: parse from JSON
            suppress_no_delim: v["suppress_no_delim"].as_bool().ok_or("FieldExtract.suppress_no_delim")?,
            output_delimiter: v["output_delimiter"].as_str().map(|s| s.to_string()),
        })
    }
}

impl crate::shir_nodes::ExtExpr for FieldExtract {
    fn tag(&self) -> &'static str { "FieldExtract" }
    fn to_json(&self) -> serde_json::Value {
        serde_json::json!({
            "type": "FieldExtract",
            "text": crate::shir_nodes::enc::expr_to_json(&self.text),
            "delimiter": self.delimiter,
            "fields": self.fields,
            "suppress_no_delim": self.suppress_no_delim,
            "output_delimiter": self.output_delimiter,
        })
    }
    fn children_mut(&mut self) -> Vec<&mut IrExpr> { vec![&mut self.text] }
    fn children(&self) -> Vec<&IrExpr> { vec![&self.text] }
    fn clone_box(&self) -> Box<dyn crate::shir_nodes::ExtExpr> { Box::new(self.clone()) }
    fn as_any(&self) -> &dyn std::any::Any { self }
}

// ── CharExtract ──────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq)]
pub struct CharExtract {
    pub text: IrExpr,
    pub byte_mode: bool,
}

impl CharExtract {
    pub(crate) fn from_json(v: &serde_json::Value) -> Result<Self, String> {
        Ok(CharExtract {
            text: crate::shir_nodes::enc::json_to_expr(&v["text"])?,
            byte_mode: v["byte_mode"].as_bool().ok_or("CharExtract.byte_mode")?,
        })
    }
}

impl crate::shir_nodes::ExtExpr for CharExtract {
    fn tag(&self) -> &'static str { "CharExtract" }
    fn to_json(&self) -> serde_json::Value {
        serde_json::json!({
            "type": "CharExtract",
            "text": crate::shir_nodes::enc::expr_to_json(&self.text),
            "byte_mode": self.byte_mode,
        })
    }
    fn children_mut(&mut self) -> Vec<&mut IrExpr> { vec![&mut self.text] }
    fn children(&self) -> Vec<&IrExpr> { vec![&self.text] }
    fn clone_box(&self) -> Box<dyn crate::shir_nodes::ExtExpr> { Box::new(self.clone()) }
    fn as_any(&self) -> &dyn std::any::Any { self }
}

// ── CharTranslate ────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq)]
pub struct CharTranslate {
    pub text: IrExpr,
    pub from: String,
    pub to: String,
    pub delete: bool,
    pub squeeze: bool,
}

impl CharTranslate {
    pub(crate) fn from_json(v: &serde_json::Value) -> Result<Self, String> {
        Ok(CharTranslate {
            text: crate::shir_nodes::enc::json_to_expr(&v["text"])?,
            from: v["from"].as_str().ok_or("CharTranslate.from")?.to_string(),
            to: v["to"].as_str().ok_or("CharTranslate.to")?.to_string(),
            delete: v["delete"].as_bool().ok_or("CharTranslate.delete")?,
            squeeze: v["squeeze"].as_bool().ok_or("CharTranslate.squeeze")?,
        })
    }
}

impl crate::shir_nodes::ExtExpr for CharTranslate {
    fn tag(&self) -> &'static str { "CharTranslate" }
    fn to_json(&self) -> serde_json::Value {
        serde_json::json!({
            "type": "CharTranslate",
            "text": crate::shir_nodes::enc::expr_to_json(&self.text),
            "from": self.from,
            "to": self.to,
            "delete": self.delete,
            "squeeze": self.squeeze,
        })
    }
    fn children_mut(&mut self) -> Vec<&mut IrExpr> { vec![&mut self.text] }
    fn children(&self) -> Vec<&IrExpr> { vec![&self.text] }
    fn clone_box(&self) -> Box<dyn crate::shir_nodes::ExtExpr> { Box::new(self.clone()) }
    fn as_any(&self) -> &dyn std::any::Any { self }
}

// ── RegSub ───────────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq)]
pub struct RegSub {
    pub text: IrExpr,
    pub pattern: String,
    pub replacement: String,
    pub global: bool,
    pub line_mode: bool,
}

impl RegSub {
    pub(crate) fn from_json(v: &serde_json::Value) -> Result<Self, String> {
        Ok(RegSub {
            text: crate::shir_nodes::enc::json_to_expr(&v["text"])?,
            pattern: v["pattern"].as_str().ok_or("RegSub.pattern")?.to_string(),
            replacement: v["replacement"].as_str().ok_or("RegSub.replacement")?.to_string(),
            global: v["global"].as_bool().ok_or("RegSub.global")?,
            line_mode: v["line_mode"].as_bool().ok_or("RegSub.line_mode")?,
        })
    }
}

impl crate::shir_nodes::ExtExpr for RegSub {
    fn tag(&self) -> &'static str { "RegSub" }
    fn to_json(&self) -> serde_json::Value {
        serde_json::json!({
            "type": "RegSub",
            "text": crate::shir_nodes::enc::expr_to_json(&self.text),
            "pattern": self.pattern,
            "replacement": self.replacement,
            "global": self.global,
            "line_mode": self.line_mode,
        })
    }
    fn children_mut(&mut self) -> Vec<&mut IrExpr> { vec![&mut self.text] }
    fn children(&self) -> Vec<&IrExpr> { vec![&self.text] }
    fn clone_box(&self) -> Box<dyn crate::shir_nodes::ExtExpr> { Box::new(self.clone()) }
    fn as_any(&self) -> &dyn std::any::Any { self }
}

// ── TakeLines ────────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq)]
pub struct TakeLines {
    pub text: IrExpr,
    pub count: IrExpr,
    pub from_end: bool,
    pub bytes: bool,
}

impl TakeLines {
    pub(crate) fn from_json(v: &serde_json::Value) -> Result<Self, String> {
        Ok(TakeLines {
            text: crate::shir_nodes::enc::json_to_expr(&v["text"])?,
            count: crate::shir_nodes::enc::json_to_expr(&v["count"])?,
            from_end: v["from_end"].as_bool().ok_or("TakeLines.from_end")?,
            bytes: v["bytes"].as_bool().ok_or("TakeLines.bytes")?,
        })
    }
}

impl crate::shir_nodes::ExtExpr for TakeLines {
    fn tag(&self) -> &'static str { "TakeLines" }
    fn to_json(&self) -> serde_json::Value {
        serde_json::json!({
            "type": "TakeLines",
            "text": crate::shir_nodes::enc::expr_to_json(&self.text),
            "count": crate::shir_nodes::enc::expr_to_json(&self.count),
            "from_end": self.from_end,
            "bytes": self.bytes,
        })
    }
    fn children_mut(&mut self) -> Vec<&mut IrExpr> { vec![&mut self.text, &mut self.count] }
    fn children(&self) -> Vec<&IrExpr> { vec![&self.text, &self.count] }
    fn clone_box(&self) -> Box<dyn crate::shir_nodes::ExtExpr> { Box::new(self.clone()) }
    fn as_any(&self) -> &dyn std::any::Any { self }
}

// ── WordCount ────────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq)]
pub struct WordCount {
    pub text: IrExpr,
    pub mode: String,
}

impl WordCount {
    pub(crate) fn from_json(v: &serde_json::Value) -> Result<Self, String> {
        Ok(WordCount {
            text: crate::shir_nodes::enc::json_to_expr(&v["text"])?,
            mode: v["mode"].as_str().ok_or("WordCount.mode")?.to_string(),
        })
    }
}

impl crate::shir_nodes::ExtExpr for WordCount {
    fn tag(&self) -> &'static str { "WordCount" }
    fn to_json(&self) -> serde_json::Value {
        serde_json::json!({
            "type": "WordCount",
            "text": crate::shir_nodes::enc::expr_to_json(&self.text),
            "mode": self.mode,
        })
    }
    fn children_mut(&mut self) -> Vec<&mut IrExpr> { vec![&mut self.text] }
    fn children(&self) -> Vec<&IrExpr> { vec![&self.text] }
    fn clone_box(&self) -> Box<dyn crate::shir_nodes::ExtExpr> { Box::new(self.clone()) }
    fn as_any(&self) -> &dyn std::any::Any { self }
}

// ── SubStrExtract ────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq)]
pub struct SubStrExtract {
    pub text: IrExpr,
    pub offset: IrExpr,
    pub length: Option<Box<IrExpr>>,
}

impl SubStrExtract {
    pub(crate) fn from_json(v: &serde_json::Value) -> Result<Self, String> {
        Ok(SubStrExtract {
            text: crate::shir_nodes::enc::json_to_expr(&v["text"])?,
            offset: crate::shir_nodes::enc::json_to_expr(&v["offset"])?,
            length: if v["length"].is_null() { None } else { Some(Box::new(crate::shir_nodes::enc::json_to_expr(&v["length"])?)) },
        })
    }
}

impl crate::shir_nodes::ExtExpr for SubStrExtract {
    fn tag(&self) -> &'static str { "SubStrExtract" }
    fn to_json(&self) -> serde_json::Value {
        serde_json::json!({
            "type": "SubStrExtract",
            "text": crate::shir_nodes::enc::expr_to_json(&self.text),
            "offset": crate::shir_nodes::enc::expr_to_json(&self.offset),
            "length": self.length.as_ref().map(|e| crate::shir_nodes::enc::expr_to_json(e)),
        })
    }
    fn children_mut(&mut self) -> Vec<&mut IrExpr> {
        let mut out = vec![&mut self.text, &mut self.offset];
        if let Some(ref mut e) = self.length { out.push(e); }
        out
    }
    fn children(&self) -> Vec<&IrExpr> {
        let mut out = vec![&self.text, &self.offset];
        if let Some(ref e) = self.length { out.push(e); }
        out
    }
    fn clone_box(&self) -> Box<dyn crate::shir_nodes::ExtExpr> { Box::new(self.clone()) }
    fn as_any(&self) -> &dyn std::any::Any { self }
}

// ── StrLen ───────────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq)]
pub struct StrLen {
    pub text: IrExpr,
}

impl StrLen {
    pub(crate) fn from_json(v: &serde_json::Value) -> Result<Self, String> {
        Ok(StrLen {
            text: crate::shir_nodes::enc::json_to_expr(&v["text"])?,
        })
    }
}

impl crate::shir_nodes::ExtExpr for StrLen {
    fn tag(&self) -> &'static str { "StrLen" }
    fn to_json(&self) -> serde_json::Value {
        serde_json::json!({
            "type": "StrLen",
            "text": crate::shir_nodes::enc::expr_to_json(&self.text),
        })
    }
    fn children_mut(&mut self) -> Vec<&mut IrExpr> { vec![&mut self.text] }
    fn children(&self) -> Vec<&IrExpr> { vec![&self.text] }
    fn clone_box(&self) -> Box<dyn crate::shir_nodes::ExtExpr> { Box::new(self.clone()) }
    fn as_any(&self) -> &dyn std::any::Any { self }
}

// ── StringContains ───────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq)]
pub struct StringContains {
    pub text: IrExpr,
    pub pattern: IrExpr,
}

impl StringContains {
    pub(crate) fn from_json(v: &serde_json::Value) -> Result<Self, String> {
        Ok(StringContains {
            text: crate::shir_nodes::enc::json_to_expr(&v["text"])?,
            pattern: crate::shir_nodes::enc::json_to_expr(&v["pattern"])?,
        })
    }
}

impl crate::shir_nodes::ExtExpr for StringContains {
    fn tag(&self) -> &'static str { "StringContains" }
    fn to_json(&self) -> serde_json::Value {
        serde_json::json!({
            "type": "StringContains",
            "text": crate::shir_nodes::enc::expr_to_json(&self.text),
            "pattern": crate::shir_nodes::enc::expr_to_json(&self.pattern),
        })
    }
    fn children_mut(&mut self) -> Vec<&mut IrExpr> { vec![&mut self.text, &mut self.pattern] }
    fn children(&self) -> Vec<&IrExpr> { vec![&self.text, &self.pattern] }
    fn clone_box(&self) -> Box<dyn crate::shir_nodes::ExtExpr> { Box::new(self.clone()) }
    fn as_any(&self) -> &dyn std::any::Any { self }
}

// ── StringAffix ──────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq)]
pub struct StringAffix {
    pub text: IrExpr,
    pub pattern: IrExpr,
    pub prefix: bool,
}

impl StringAffix {
    pub(crate) fn from_json(v: &serde_json::Value) -> Result<Self, String> {
        Ok(StringAffix {
            text: crate::shir_nodes::enc::json_to_expr(&v["text"])?,
            pattern: crate::shir_nodes::enc::json_to_expr(&v["pattern"])?,
            prefix: v["prefix"].as_bool().ok_or("StringAffix.prefix")?,
        })
    }
}

impl crate::shir_nodes::ExtExpr for StringAffix {
    fn tag(&self) -> &'static str { "StringAffix" }
    fn to_json(&self) -> serde_json::Value {
        serde_json::json!({
            "type": "StringAffix",
            "text": crate::shir_nodes::enc::expr_to_json(&self.text),
            "pattern": crate::shir_nodes::enc::expr_to_json(&self.pattern),
            "prefix": self.prefix,
        })
    }
    fn children_mut(&mut self) -> Vec<&mut IrExpr> { vec![&mut self.text, &mut self.pattern] }
    fn children(&self) -> Vec<&IrExpr> { vec![&self.text, &self.pattern] }
    fn clone_box(&self) -> Box<dyn crate::shir_nodes::ExtExpr> { Box::new(self.clone()) }
    fn as_any(&self) -> &dyn std::any::Any { self }
}

// ── StringTrim ───────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq)]
pub struct StringTrim {
    pub text: IrExpr,
    pub leading: bool,
    pub trailing: bool,
}

impl StringTrim {
    pub(crate) fn from_json(v: &serde_json::Value) -> Result<Self, String> {
        Ok(StringTrim {
            text: crate::shir_nodes::enc::json_to_expr(&v["text"])?,
            leading: v["leading"].as_bool().ok_or("StringTrim.leading")?,
            trailing: v["trailing"].as_bool().ok_or("StringTrim.trailing")?,
        })
    }
}

impl crate::shir_nodes::ExtExpr for StringTrim {
    fn tag(&self) -> &'static str { "StringTrim" }
    fn to_json(&self) -> serde_json::Value {
        serde_json::json!({
            "type": "StringTrim",
            "text": crate::shir_nodes::enc::expr_to_json(&self.text),
            "leading": self.leading,
            "trailing": self.trailing,
        })
    }
    fn children_mut(&mut self) -> Vec<&mut IrExpr> { vec![&mut self.text] }
    fn children(&self) -> Vec<&IrExpr> { vec![&self.text] }
    fn clone_box(&self) -> Box<dyn crate::shir_nodes::ExtExpr> { Box::new(self.clone()) }
    fn as_any(&self) -> &dyn std::any::Any { self }
}

// ── RepeatStr ────────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq)]
pub struct RepeatStr {
    pub text: IrExpr,
    pub count: IrExpr,
}

impl RepeatStr {
    pub(crate) fn from_json(v: &serde_json::Value) -> Result<Self, String> {
        Ok(RepeatStr {
            text: crate::shir_nodes::enc::json_to_expr(&v["text"])?,
            count: crate::shir_nodes::enc::json_to_expr(&v["count"])?,
        })
    }
}

impl crate::shir_nodes::ExtExpr for RepeatStr {
    fn tag(&self) -> &'static str { "RepeatStr" }
    fn to_json(&self) -> serde_json::Value {
        serde_json::json!({
            "type": "RepeatStr",
            "text": crate::shir_nodes::enc::expr_to_json(&self.text),
            "count": crate::shir_nodes::enc::expr_to_json(&self.count),
        })
    }
    fn children_mut(&mut self) -> Vec<&mut IrExpr> { vec![&mut self.text, &mut self.count] }
    fn children(&self) -> Vec<&IrExpr> { vec![&self.text, &self.count] }
    fn clone_box(&self) -> Box<dyn crate::shir_nodes::ExtExpr> { Box::new(self.clone()) }
    fn as_any(&self) -> &dyn std::any::Any { self }
}

// ── CaseTransform ────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq)]
pub struct CaseTransform {
    pub text: IrExpr,
    pub upper: bool,
}

impl CaseTransform {
    pub(crate) fn from_json(v: &serde_json::Value) -> Result<Self, String> {
        Ok(CaseTransform {
            text: crate::shir_nodes::enc::json_to_expr(&v["text"])?,
            upper: v["upper"].as_bool().ok_or("CaseTransform.upper")?,
        })
    }
}

impl crate::shir_nodes::ExtExpr for CaseTransform {
    fn tag(&self) -> &'static str { "CaseTransform" }
    fn to_json(&self) -> serde_json::Value {
        serde_json::json!({
            "type": "CaseTransform",
            "text": crate::shir_nodes::enc::expr_to_json(&self.text),
            "upper": self.upper,
        })
    }
    fn children_mut(&mut self) -> Vec<&mut IrExpr> { vec![&mut self.text] }
    fn children(&self) -> Vec<&IrExpr> { vec![&self.text] }
    fn clone_box(&self) -> Box<dyn crate::shir_nodes::ExtExpr> { Box::new(self.clone()) }
    fn as_any(&self) -> &dyn std::any::Any { self }
}

// ── Registry ─────────────────────────────────────────────────────────

pub(crate) fn all_expr_nodes() -> Vec<(&'static str, crate::shir_nodes::ExprNodeCtor)> {
    vec![
        ("CaseTransform", |v| Ok(Box::new(CaseTransform::from_json(v)?))),
        ("CharExtract", |v| Ok(Box::new(CharExtract::from_json(v)?))),
        ("CharTranslate", |v| Ok(Box::new(CharTranslate::from_json(v)?))),
        ("FieldExtract", |v| Ok(Box::new(FieldExtract::from_json(v)?))),
        ("RegSub", |v| Ok(Box::new(RegSub::from_json(v)?))),
        ("RepeatStr", |v| Ok(Box::new(RepeatStr::from_json(v)?))),
        ("StrLen", |v| Ok(Box::new(StrLen::from_json(v)?))),
        ("StringAffix", |v| Ok(Box::new(StringAffix::from_json(v)?))),
        ("StringContains", |v| Ok(Box::new(StringContains::from_json(v)?))),
        ("StringTrim", |v| Ok(Box::new(StringTrim::from_json(v)?))),
        ("SubStrExtract", |v| Ok(Box::new(SubStrExtract::from_json(v)?))),
        ("TakeLines", |v| Ok(Box::new(TakeLines::from_json(v)?))),
        ("WordCount", |v| Ok(Box::new(WordCount::from_json(v)?))),
    ]
}
