// @generated by build.rs from src/shir_nodes/*.node — do not edit.
// (scratch copy for compilation verification)

// ── CountedFor ───────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq)]
pub struct CountedFor {
    pub var: String,
    pub init: i64,
    pub step: i64,
    pub cond: crate::ir::IrExpr,
    pub body: Vec<crate::ir::IrStmt>,
}

impl CountedFor {
    pub(crate) fn from_json(v: &serde_json::Value) -> Result<Self, String> {
        Ok(CountedFor {
            var: v["var"].as_str().ok_or("CountedFor.var")?.to_string(),
            init: v["init"].as_i64().ok_or("CountedFor.init")?,
            step: v["step"].as_i64().ok_or("CountedFor.step")?,
            cond: crate::shir_nodes::enc::json_to_expr(&v["cond"])?,
            body: crate::shir_nodes::enc::json_to_stmts(&v["body"])?,
        })
    }
}

impl crate::shir_nodes::ExtNode for CountedFor {
    fn tag(&self) -> &'static str { "CountedFor" }
    fn to_json(&self) -> serde_json::Value {
        serde_json::json!({
            "type": "CountedFor",
            "var": self.var,
            "init": self.init,
            "step": self.step,
            "cond": crate::shir_nodes::enc::expr_to_json(&self.cond),
            "body": crate::shir_nodes::enc::stmts_to_json(&self.body),
        })
    }
    fn children_mut(&mut self) -> Vec<&mut crate::ir::IrStmt> {
        let mut out = Vec::new();
        out.extend(self.body.iter_mut());
        out
    }
    fn children(&self) -> Vec<&crate::ir::IrStmt> {
        let mut out = Vec::new();
        out.extend(self.body.iter());
        out
    }
    fn clone_box(&self) -> Box<dyn crate::shir_nodes::ExtNode> { Box::new(self.clone()) }
    fn as_any(&self) -> &dyn std::any::Any { self }
}

// ── Registry ─────────────────────────────────────────────────────────

pub(crate) fn all_nodes() -> Vec<(&'static str, crate::shir_nodes::NodeCtor)> {
    vec![
        ("CountedFor", |v| Ok(Box::new(CountedFor::from_json(v)?))),
    ]
}
